server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/transaction
    username: root
    password: 1996921
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
      rest:
        base-path: /
        default-page-size: 10
        default-page-number: 0
        page-param-name: pageNum
        sort-param-name: sort
        limit-param-name: pageSize
  img:
    location: G:\transaction\img
    url: http://192.168.1.100:8088/images/
    #url: http://192.168.43.231:8088/images/
