server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/transaction?characterEncoding=utf8&useSSL=true&useUnicode=true&serverTimezone=UTC
    username: root
    password: imagedt
#  jpa:
#    hibernate:
#      ddl-auto: update
#      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    show-sql: true
  data:
      rest:
        base-path: /
        default-page-size: 10
        default-page-number: 0
        page-param-name: pageNum
        sort-param-name: sort
        limit-param-name: pageSize
  img:
    location: E:/test/shopWeixin-SecondhandShop/image
    url : /image/
    #url : http://127.0.0.1:8081/static/images/
  mvc:
    view:
      prefix: /static/
      suffix: .html
    static-path-pattern: /**
#    url: http://192.168.1.100:8088/images/
    #url: http://192.168.43.231:8088/images/

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true

pagehelper:
  helperDialect: mysql
  pageSizeZero: true